### ISSUE TITLE
github上的用法文档写错了

### ISSUE THREAD

**Issue by wubinhong** [zedwang/angular-kindeditor#4]
`<div class="keditor" ng-model="content"></div>`
应该换成
`<textarea keditor ng-model="content" data-config="config" cols="30" rows="10" required></textarea>`
或者

`<div keditor ng-model="content" data-config="config"></div>`

希望能更正文档，东西不错，谢谢了，加油！

**Comment by wubinhong** [comment]
<div class="keditor" ng-model="content"></div>
应该换成
<textarea keditor ng-model="content" data-config="config" cols="30" rows="10" required></textarea>
或者
<div keditor ng-model="content" data-config="config"></div>

希望能更正文档，东西不错，谢谢了，加油！

**Comment by zedwang** [comment]
3Q!已更正.
