### ISSUE TITLE
请问文件上传怎么配置？

### ISSUE THREAD

**Issue by RobinWooo** [zedwang/angular-kindeditor#7]

**Comment by zedwang** [comment]
请参考kindeditor的官方文档.

------------------ 原始邮件 ------------------
发件人: "HowardWong";notifications@github.com;
发送时间: 2016年9月9日(星期五) 下午4:21
收件人: "zedwang/angular-kindeditor"angular-kindeditor@noreply.github.com; 

主题: Re: [zedwang/angular-kindeditor] 请问文件上传怎么配置？ (#7)

Closed #7.
